"""empty message

Revision ID: 94f161906862
Revises: 1048f877b9fb
Create Date: 2023-05-08 16:24:17.235251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f161906862'
down_revision = '1048f877b9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('create_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_data', sa.DATETIME(), nullable=False))
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
